language: php
php:
  - 7.2
  - 7.3
  - 7.4
  before_install:
  - cd ~
  - composer create-project drupal/recommended-project trichechus-test --stability dev --no-interaction
  - cd trichechus-test
  - composer config repositories.trichechus path $TRAVIS_BUILD_DIR
  - composer config extra.enable-patching true
before_script:
  - cd ~/trichechus-test
  - composer require manaticr/trichechus:"*"
script:
  - cd ~/trichechus-test
  - mkdir web/libraries
  - ln -s $PWD/vendor/enyo/dropzone $PWD/web/libraries/dropzone
  - ./vendor/bin/drush si trichechus -y --db-url=sqlite://tmp/.ht.sqlite
