language: php
php:
  - 7.1
  - 7.2
before_install:
  - cd ~
  - composer create-project drupal-composer/drupal-project:8.x-dev trichechus-test --stability dev --no-interaction
  - cd trichechus-test
  - composer config repositories.trichechus path $TRAVIS_BUILD_DIR
before_script:
  - cd ~/trichechus-test
  - composer require manaticr/trichechus:"dev-$TRAVIS_COMMIT"
script:
  - cd ~/trichechus-test
  - ls web/profiles/
  - ls web/profiles/contrib
  - ls web/modules/contrib
  - ln -s $PWD/vendor/enyo/dropzone $PWD/web/libraries/dropzone
  - ./vendor/bin/drush si trichechus -y --db-url=sqlite://tmp/.ht.sqlite
